[package]
name = "termscp"
version = "0.1.0"
authors = ["Christian Visintin"]
edition = "2018"
license = "GPL-3.0"
keywords = ["scp-client", "sftp-client", "ftp-client", "winscp", "command-line-utility"]
categories = ["command-line-utilities"]
description = "TermSCP is a SCP/SFTP/FTPS client for command line with an integrated UI to explore the remote file system. Basically WinSCP on a terminal."
homepage = "https://github.com/ChristianVisintin/TermSCP"
repository = "https://github.com/ChristianVisintin/TermSCP"
documentation = "https://docs.rs/termscp"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.18.2"
getopts = "0.2.21"
ssh2 = "0.8.2"
tui = { version = "0.12.0", features = ["crossterm"], default-features = false }
users = "0.11.0"
whoami = "0.9.0"
rpassword = "5.0.0"
unicode-width = "0.1.7"
chrono = "0.4.19"
bytesize = "1.0.1"

[dev-dependencies]
tempfile = "3"

[[bin]]
name = "termscp"
path = "src/main.rs"
