[package]
name = "termscp"
version = "0.1.1"
authors = ["Christian Visintin"]
edition = "2018"
license = "GPL-3.0"
keywords = ["scp-client", "sftp-client", "ftp-client", "winscp", "command-line-utility"]
categories = ["command-line-utilities"]
description = "TermSCP is a SCP/SFTP/FTPS client for command line with an integrated UI to explore the remote file system. Basically WinSCP on a terminal."
homepage = "https://github.com/ChristianVisintin/TermSCP"
repository = "https://github.com/ChristianVisintin/TermSCP"
documentation = "https://docs.rs/termscp"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.18.2"
ftp4 = { version = "^4.0.0", features = ["secure"] }
getopts = "0.2.21"
ssh2 = "0.9.0"
tui = { version = "0.13.0", features = ["crossterm"], default-features = false }
whoami = "1.0.0"
rpassword = "5.0.0"
unicode-width = "0.1.7"
chrono = "0.4.19"
bytesize = "1.0.1"
textwrap = "0.12.1"
regex = "1.4.2"
lazy_static = "1.4.0"
hostname = "0.3.1"

[target.'cfg(any(unix, macos, linux))'.dependencies]
users = "0.11.0"

[dev-dependencies]
tempfile = "3"

#[patch.crates-io]
#ftp = { git = "https://github.com/ChristianVisintin/rust-ftp" }

[[bin]]
name = "termscp"
path = "src/main.rs"

[package.metadata.rpm]
package = "termscp"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
termscp = { path = "/usr/bin/termscp" }
