auth_address = "Yellow"
auth_bookmarks = "skyblue"
auth_password = "#c43bff"
auth_port = "lime"
auth_protocol = "orangered"
auth_recents = "deepskyblue"
auth_username = "aqua"
misc_error_dialog = "crimson"
misc_input_dialog = "turquoise"
misc_keys = "deeppink"
misc_quit_dialog = "lime"
misc_save_dialog = "gold"
misc_warn_dialog = "orangered"
transfer_local_explorer_background = "Default"
transfer_local_explorer_foreground = "Default"
transfer_local_explorer_highlighted = "aquamarine"
transfer_log_background = "Default"
transfer_log_window = "#c43bff"
transfer_progress_bar_full = "deeppink"
transfer_progress_bar_partial = "turquoise"
transfer_remote_explorer_background = "Default"
transfer_remote_explorer_foreground = "Default"
transfer_remote_explorer_highlighted = "greenyellow"
transfer_status_hidden = "lime"
transfer_status_sorting = "orangered"
transfer_status_sync_browsing = "darkturquoise"
