auth_address = "salmon"
auth_bookmarks = "cornflowerblue"
auth_password = "crimson"
auth_port = "tomato"
auth_protocol = "coral"
auth_recents = "royalblue"
auth_username = "orangered"
misc_error_dialog = "crimson"
misc_input_dialog = "gold"
misc_keys = "deeppink"
misc_quit_dialog = "coral"
misc_save_dialog = "tomato"
misc_warn_dialog = "orangered"
transfer_local_explorer_background = "Default"
transfer_local_explorer_foreground = "lightcoral"
transfer_local_explorer_highlighted = "coral"
transfer_log_background = "Default"
transfer_log_window = "royalblue"
transfer_progress_bar_full = "hotpink"
transfer_progress_bar_partial = "deeppink"
transfer_remote_explorer_background = "Default"
transfer_remote_explorer_foreground = "lightsalmon"
transfer_remote_explorer_highlighted = "salmon"
transfer_status_hidden = "orange"
transfer_status_sorting = "gold"
transfer_status_sync_browsing = "tomato"
