auth_address = "white"
auth_bookmarks = "white"
auth_password = "white"
auth_port = "white"
auth_protocol = "white"
auth_recents = "white"
auth_username = "white"
misc_error_dialog = "white"
misc_input_dialog = "white"
misc_keys = "white"
misc_quit_dialog = "white"
misc_save_dialog = "white"
misc_warn_dialog = "white"
transfer_local_explorer_background = "Default"
transfer_local_explorer_foreground = "Default"
transfer_local_explorer_highlighted = "white"
transfer_log_background = "Default"
transfer_log_window = "white"
transfer_progress_bar_full = "white"
transfer_progress_bar_partial = "white"
transfer_remote_explorer_background = "Default"
transfer_remote_explorer_foreground = "Default"
transfer_remote_explorer_highlighted = "white"
transfer_status_hidden = "white"
transfer_status_sorting = "white"
transfer_status_sync_browsing = "white"
