auth_address = "black"
auth_bookmarks = "#bbbbbb"
auth_password = "black"
auth_port = "black"
auth_protocol = "black"
auth_recents = "#bbbbbb"
auth_username = "black"
misc_error_dialog = "black"
misc_info_dialog = "black"
misc_input_dialog = "black"
misc_keys = "black"
misc_quit_dialog = "black"
misc_save_dialog = "black"
misc_warn_dialog = "black"
transfer_local_explorer_background = "Default"
transfer_local_explorer_foreground = "Default"
transfer_local_explorer_highlighted = "#bbbbbb"
transfer_log_background = "Default"
transfer_log_window = "black"
transfer_progress_bar_full = "black"
transfer_progress_bar_partial = "black"
transfer_remote_explorer_background = "Default"
transfer_remote_explorer_foreground = "Default"
transfer_remote_explorer_highlighted = "#bbbbbb"
transfer_status_hidden = "black"
transfer_status_sorting = "black"
transfer_status_sync_browsing = "black"
