auth_address = "hotpink"
auth_bookmarks = "pink"
auth_password = "violet"
auth_port = "plum"
auth_protocol = "deeppink"
auth_recents = "lightpink"
auth_username = "orchid"
misc_error_dialog = "mediumvioletred"
misc_input_dialog = "plum"
misc_keys = "deeppink"
misc_quit_dialog = "lightcoral"
misc_save_dialog = "violet"
misc_warn_dialog = "hotpink"
transfer_local_explorer_background = "Default"
transfer_local_explorer_foreground = "pink"
transfer_local_explorer_highlighted = "hotpink"
transfer_log_background = "Default"
transfer_log_window = "palevioletred"
transfer_progress_bar_full = "hotpink"
transfer_progress_bar_partial = "deeppink"
transfer_remote_explorer_background = "Default"
transfer_remote_explorer_foreground = "plum"
transfer_remote_explorer_highlighted = "violet"
transfer_status_hidden = "violet"
transfer_status_sorting = "plum"
transfer_status_sync_browsing = "orchid"
