auth_address = "LightYellow"
auth_bookmarks = "springgreen"
auth_password = "deepskyblue"
auth_port = "LightCyan"
auth_protocol = "LightGreen"
auth_recents = "aquamarine"
auth_username = "hotpink"
misc_error_dialog = "orangered"
misc_input_dialog = "snow"
misc_keys = "LightCyan"
misc_quit_dialog = "LightYellow"
misc_save_dialog = "LightCyan"
misc_warn_dialog = "tomato"
transfer_local_explorer_background = "Default"
transfer_local_explorer_foreground = "Default"
transfer_local_explorer_highlighted = "Yellow"
transfer_log_background = "Default"
transfer_log_window = "lawngreen"
transfer_progress_bar = "lawngreen"
transfer_remote_explorer_background = "Default"
transfer_remote_explorer_foreground = "Default"
transfer_remote_explorer_highlighted = "turquoise"
transfer_status_hidden = "deepskyblue"
transfer_status_sorting = "LightYellow"
transfer_status_sync_browsing = "LightGreen"
