auth_address = "Yellow"
auth_bookmarks = "plum"
auth_password = "LightBlue"
auth_port = "turquoise"
auth_protocol = "greenyellow"
auth_recents = "paleturquoise"
auth_username = "deeppink"
misc_error_dialog = "crimson"
misc_input_dialog = "snow"
misc_keys = "deeppink"
misc_quit_dialog = "tomato"
misc_save_dialog = "gold"
misc_warn_dialog = "orangered"
transfer_local_explorer_background = "Default"
transfer_local_explorer_foreground = "Default"
transfer_local_explorer_highlighted = "orange"
transfer_log_background = "Default"
transfer_log_window = "limegreen"
transfer_progress_bar_full = "lawngreen"
transfer_progress_bar_partial = "limegreen"
transfer_remote_explorer_background = "Default"
transfer_remote_explorer_foreground = "Default"
transfer_remote_explorer_highlighted = "turquoise"
transfer_status_hidden = "dodgerblue"
transfer_status_sorting = "LightYellow"
transfer_status_sync_browsing = "palegreen"
